name: Cropper
version: '${version}'
main: net.eve0415.cropper.Cropper
api-version: 1.19
authors: [ eve0415 ]
description: Add some useful system for crops and trees
website: https://github.com/eve0415/cropper
libraries:
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.6.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.6.0
